import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineUserGroup,
  HiOutlineLightBulb,
  HiOutlineClock,
  HiOutlineClipboardDocumentList,
  HiOutlineChatBubbleLeftRight,
  HiOutlineAdjustmentsHorizontal,
  HiOutlineArrowTrendingUp,
  HiOutlineShieldCheck,
  HiOutlineHandThumbUp,
  HiOutlineStar,
  HiOutlineDevicePhoneMobile,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiHtml5,
  SiCss3,
  SiReact,
  SiTailwindcss,
  SiNodedotjs,
  SiPhp,
  SiPython,
  SiGit,
  SiTypescript,
  SiLaravel,
  SiMysql,
  SiMongodb,
  SiDocker,
  SiPostman,
  SiWordpress,
  SiJira,
  SiCanva,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaChartBar, FaDiagramProject, FaDatabase, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  phone: HiOutlineDevicePhoneMobile,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  star: HiOutlineStar,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  html: SiHtml5,
  css: SiCss3,
  react: SiReact,
  tailwind: SiTailwindcss,
  nodejs: SiNodedotjs,
  php: SiPhp,
  python: SiPython,
  git: SiGit,
  typescript: SiTypescript,
  laravel: SiLaravel,
  mysql: SiMysql,
  mongodb: SiMongodb,
  docker: SiDocker,
  postman: SiPostman,
  wordpress: SiWordpress,
  jira: SiJira,
  canva: SiCanva,
  powerbi: FaChartBar,
  drawio: FaDiagramProject,
  database: FaDatabase,
  leadership: HiOutlineStar,
  teamwork: HiOutlineUserGroup,
  criticalThinking: HiOutlineLightBulb,
  timeManagement: HiOutlineClock,
  projectManagement: HiOutlineClipboardDocumentList,
  communication: HiOutlineChatBubbleLeftRight,
  adaptability: HiOutlineAdjustmentsHorizontal,
  selfMotivation: HiOutlineArrowTrendingUp,
  responsibility: HiOutlineShieldCheck,
  respect: HiOutlineHandThumbUp,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
